### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by epoz** [kbecker87/ca_iconclass#1]
Dear Karl,

Can you please add some contact details for getting in touch with you on the README page?
I have some suggestions about your plugin.

With kind regards,

Etienne Posthumus
(maker of the ICONCLASS system)

**Comment by karkraeg** [comment]
Hi Etienne,

you can email me at `karl.becker [at] outlook.com`

Thanks,

Karl

**Comment by epoz** [comment]
Great, thx.
